version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/usr/src/shipper/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=pdbuser
     - POSTGRES_PASSWORD=pdbpw_changeme
     - POSTGRES_DB=shipper

volumes:
  postgres_data:

