version: "3.8"

services:
  web:
    build:
      context: shipper
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - media_volume:/home/shipper/web/media
    - static_volume:/home/shipper/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
    - media_volume:/home/shipper/web/media
    - static_volume:/home/shipper/web/static
    ports:
      - 9200:80
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume:
  static_volume:

