

contact_links:
  - name: Security Vulnerability
    url: https://github.com/ericswpark/shipper/blob/master/SECURITY.md#reporting-a-vulnerability
    about: If you believe you have found a security vulnerability with shipper, please follow the instructions here.